# Generated by Django 3.2.7 on 2021-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userName', models.CharField(blank=True, default='こすこす', max_length=100)),
                ('userId', models.IntegerField(blank=True, default=0)),
                ('todayGoal', models.BigIntegerField(blank=True, default=0)),
                ('todayNow', models.BigIntegerField(blank=True, default=0)),
                ('weekGoal', models.BigIntegerField(blank=True, default=0)),
                ('weekNow', models.BigIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
